### ISSUE TITLE
noBias - nil value

### ISSUE THREAD

**Issue by slavakurilyak** [e-lab/torch-prednet#1]
When I run `qlua main.lua -nlayers 3 -display -save -savePics` I get

`qlua: ./convLSTM.lua:10: attempt to call method 'noBias' (a nil value)`

Any ideas?

**Comment by spk921** [comment]
Can you update your torch package ? Your torch package might be old one.
Sincerely,
Sangpil Kim

Sangpil Kim   Ph.D. ECE
Purdue University
m: +1 (765) 430-9721 a: 206 S MARTIN JISCHKE DR, BME #2058C
e: kim2030@purdue.edu, spkim921@gmail.com
https://www.facebook.com/pablo0921  https://twitter.com/spkim9211

**Comment by slavakurilyak** [comment]
Thanks, updating torch solved the issue
